name: Test Server

on:
  push:
    branches:
      - main 

jobs:
  test-server:
    runs-on: ubuntu-latest
    container: 
        image: python:3.8-slim

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        cd src
        python test.py
